# Section 4. Feature engineering

### CONTENTS
* <a href='03 - DSC 2022 Hypothesis testing.ipynb#top'>**Section 3. Hypothesis Testing**</a> 
* <a href='04- DSC 2022 Feature Engineering .ipynb#top'>**Section 4. Feature Engineering**</a> 
  * [1. Deal with NA's](#na)
  * [2. Feature creation](#create)
  * [3. Transformation](#transform)
  * [4. Put everything together](#function)
* <a href='05- DSC 2022 Modeling .ipynb#top'>**Section 5. Modeling**</a>

In [2]:
import pandas as pd 
import numpy as np

Again, we will read in the data first. In this notebook we will be making changes to the data frame. And therefore a safer way is to make a deep copy of the original data frame and make changes on the copied data so that we don't make accidental stupid changes to the original data frame. It is always good to have a backup.

In [3]:
cmg = pd.read_excel('cmg_final.xlsx', index_col = 'offeringId')
cmg_transformed = cmg.copy(deep = True)
cmg_transformed.head()

,offeringPricingDate,offeringType,offeringSector,offeringSubSector,offeringDiscountToLastTrade,offeringPrice,issuerCusip,issuerName,Pre_15SharePrice,Pre_14SharePrice,...,Pre_1SharePrice,underwriters,totalBookrunners,leftLeadFirmId,leftLeadFirmName,Post_1SharePrice,Post_7SharePrice,Post_30SharePrice,Post_90SharePrice,Post_180SharePrice
offeringId,,,,,,,,,,,,,,,,,,,,,
b969a1c8-0a26-438a-81e6-5e95f3b30501,2003-10-02,IPO,Consumer Cyclical,Vehicles & Parts,0.0,13.0,501889208,BharCap Acquisition Corp.,NaN,NaN,...,NaN,[{'firmId': '15af8b8d-c949-4fa0-b35e-a6482d3ca...,2,759ce574-3755-480b-8b83-c614f4568db1,Baird,1.875000,1.950000,2.188750,2.268750,2.125000
1081394b-c9f2-4479-8dd2-528027ff1eea,2005-07-21,IPO,Communication Services,Telecom Services,0.0,13.0,209034107,GrandSouth Bancorporation,NaN,NaN,...,NaN,[{'firmId': 'dac135c0-9e99-4362-9762-7179a0023...,2,5eb63e75-8f95-464e-86fe-3222865c54ef,Credit Suisse,13.790000,14.780000,13.540000,12.760000,12.780000
714a166d-9eb0-4b3c-ab8e-7c0dc6f21ee0,2005-08-04,IPO,Communication Services,Internet Content & Information,0.0,27.0,056752108,Brand Velocity Acquisition Corp,NaN,NaN,...,NaN,[{'firmId': 'a82a866c-d40e-453a-99e1-8acb44efb...,2,dac135c0-9e99-4362-9762-7179a0023c9e,Goldman Sachs & Co.,12.254000,9.790000,7.780000,6.850000,5.451000
43f06950-8d20-4cfc-b16d-237e0927e1e6,2005-11-10,IPO,Industrials,Consulting Services,0.0,16.0,G47567105,ProLung Inc.,NaN,NaN,...,NaN,[{'firmId': 'a82a866c-d40e-453a-99e1-8acb44efb...,2,cd9cd378-73b5-4cef-8666-ad2c5149ccd8,Goldman Sachs & Co.,4.807962,4.841702,5.075071,6.942023,7.796772
96a13598-121a-41c0-83b5-448843cd8709,2006-02-03,IPO,Energy,Oil & Gas Midstream,0.0,21.0,29273V100,Golden Star Acquisition Corp,NaN,NaN,...,NaN,[{'firmId': '7d932034-3e85-46ab-97b4-b6e8e86ee...,3,8fdb6c2d-3b35-40d4-a886-0a3461b42d98,UBS Investment Bank,5.662500,5.487500,5.447500,6.225000,6.550000

<a id='na'></a>
## 1. Deal with NA's

Recall that in our last notebook, we found that the data set contains NA's in pre-deal performance columns. However, models won't work with NA's. Two typical ways in dealing with NA's are 1)dropping observations with NAs and 2)impute the missing values. 

In this case, we probably don't want to drop the rows that contain NA's since then we would lose all observations that are IPO's. Then we are left with imputing the missing values. There are various ways in how we could impute these values. And one way could be to fill all the pre-deal price with the offering price. This is easy and straightforward but not necessarily the best way, so feel free to design your own method.

In [4]:
cmg_transformed = cmg_transformed.apply(lambda x: x.fillna(value=cmg['offeringPrice']))
cmg_transformed.isna().sum()

offeringPricingDate            0
offeringType                   0
offeringSector                 0
offeringSubSector              0
offeringDiscountToLastTrade    0
offeringPrice                  0
issuerCusip                    0
issuerName                     0
Pre_15SharePrice               0
Pre_14SharePrice               0
Pre_13SharePrice               0
Pre_12SharePrice               0
Pre_11SharePrice               0
Pre_10SharePrice               0
Pre_9SharePrice                0
Pre_8SharePrice                0
Pre_7SharePrice                0
Pre_6SharePrice                0
Pre_5SharePrice                0
Pre_4SharePrice                0
Pre_3SharePrice                0
Pre_2SharePrice                0
Pre_1SharePrice                0
underwriters                   0
totalBookrunners               0
leftLeadFirmId                 0
leftLeadFirmName               0
Post_1SharePrice               0
Post_7SharePrice               0
Post_30SharePrice              0
Post_90SharePrice              0
Post_180SharePrice             0
dtype: int64

<a id='create'></a>
## 2. Feature creation

Sometimes, variables we need for inference are not present in the given data frame. And hence we would need to create features based on what's given. 





For example, one hypothesis that we had earlier is that whether or not an issuer has changed lead banks across various deals might affect deal performance. However, in our original data frame, we don't have such an variable that is whether or not an issuer has changed lead banks. Now, it's time for us to get creative! There could be multiple ways in how we contstruct the variable. 

1. We would say say that if an issuer has ever used more than 1 lead bank, then we mark all rows as switched True. 
2. whether compared to the last deal, current deal is using a different lead bank.

In [5]:
temp = cmg.groupby(by = 'issuerCusip').size().to_frame('numOffering').sort_values('numOffering', ascending = False)
print('number of issuers that have 1 offering', sum(temp.numOffering > 1)) 
temp

number of issuers that have 1 offering 1686

             numOffering
issuerCusip
649604501             17
647551100             16
008492100             14
15677J108             12
G66721104             12
...                  ...
08653C106              1
55283P106              1
08579X101              1
084656107              1
688410208              1

[4623 rows x 1 columns]

For example, we can pull out all the offering information by the issuer 649604501 ordered by date. We now see that the issuer switched lead firm multiple times (from Ladenburg Thalmann & Co. Inc., to Deutsche Bank Securities, UBS Investment Bank and finally Morgan Stanley).

In [6]:
def queryOffering(issuerCusip):
    return cmg[cmg.issuerCusip == issuerCusip].sort_values(by = ['offeringPricingDate']).filter(items = ['offeringId', 'offeringPricingDate', 'offeringType', 'leftLeadFirmName'])

queryOffering('649604501')

,offeringPricingDate,offeringType,leftLeadFirmName
offeringId,,,
41912c5e-4348-4398-aff5-f6d1e584af53,2011-06-28,OVERNIGHT_FO,Ladenburg Thalmann & Co. Inc.
eb44b8ae-3fdc-4ff4-b468-2622007c4d45,2011-12-01,OVERNIGHT_FO,Ladenburg Thalmann & Co. Inc.
3a7c2db7-93f1-4141-9a89-622b69820414,2012-05-25,OVERNIGHT_FO,Ladenburg Thalmann & Co. Inc.
f6002e6f-1258-4f89-8625-e740414f103d,2012-07-12,OVERNIGHT_FO,Ladenburg Thalmann & Co. Inc.
4b7d3caf-bc85-4b97-ad03-863d0ecb8fef,2012-08-16,OVERNIGHT_FO,Deutsche Bank Securities
4daf79f9-4eb2-4ea4-a9a6-c121040703c1,2012-10-03,OVERNIGHT_FO,Deutsche Bank Securities
d351fe2d-d1ac-47b5-8aa4-7677f0e40091,2013-04-29,REGISTERED_BLOCK,Deutsche Bank Securities
42f3b9ed-e84f-40f6-9da2-edcf04923568,2014-01-07,OVERNIGHT_FO,UBS Investment Bank
9e5b0b4b-e947-4000-a4d0-f54407d66363,2014-04-02,OVERNIGHT_FO,UBS Investment Bank
c753d0d3-e132-4dd3-b1e0-f4bc03fdfba9,2014-11-21,OVERNIGHT_FO,UBS Investment Bank
4ef23416-abd7-44ef-bfbb-cbbeae73ac41,2019-02-26,REGISTERED_BLOCK,Morgan Stanley
b31aff89-4477-4b24-b470-cbce65dd975f,2019-05-08,REGISTERED_BLOCK,Morgan Stanley
7c4a8567-acb2-44e9-8e25-3852086b9d7a,2019-07-17,REGISTERED_BLOCK,Morgan Stanley
14d12500-c97f-4049-9731-9263132b2721,2019-09-10,REGISTERED_BLOCK,Morgan Stanley
8edb1baf-ccec-4c60-9290-4797018d51fd,2019-11-19,REGISTERED_BLOCK,Morgan Stanley
06473c01-0ae9-488f-a062-5fc051370dc9,2020-01-07,REGISTERED_BLOCK,Morgan Stanley
d7bef16f-9904-42a7-a85a-58d204c3aa31,2020-02-10,REGISTERED_BLOCK,Morgan Stanley

a. We define whether or not change bank on an issuer level. If an issuer is associated with various left lead firms across different deals, then we mark all offerings We could define whether or not change bank to be whether issuers have changed their banks across different offerings. That is, if an issuer has an

In [7]:
# issuers that have change their banks 
temp = cmg.groupby(['issuerCusip']).agg({'leftLeadFirmName': lambda x: list(x.unique())})
temp['changeBank'] = temp['leftLeadFirmName'].apply(lambda x: True if (len(x) > 1) else False)
print('numbers of issuers that change their banks ', len(temp[temp.changeBank == True])) 
temp

numbers of issuers that change their banks  1193

                                          leftLeadFirmName  changeBank
issuerCusip
000307108                   [William Blair, Raymond James]        True
000380204                                 [Morgan Stanley]       False
00081T108                                  [Credit Suisse]       False
00085X105                                        [Chardan]       False
000899104    [Oppenheimer & Co., Raymond James, Jefferies]        True
...                                                    ...         ...
Y8565N300                                      [Citigroup]       False
Y8977Y100                                 [Morgan Stanley]       False
Y93691106                            [Goldman Sachs & Co.]       False
Y9384M101                         [Citigroup, J.P. Morgan]        True
Y95308105                                      [Jefferies]       False

[4623 rows x 2 columns]

In [ ]:
b. We define whether or not change bank on an offering level. If an# offerings that have a change from the previous offering

In [8]:
temp = cmg.filter(items = ['offeringId', 'issuerCusip', 'offeringPricingDate', 'leftLeadFirmName']).sort_values(by = ['issuerCusip', 'offeringPricingDate'])
temp['lagLeftLeadFirmName'] = temp['leftLeadFirmName'].shift(1)
temp['lagissuerCusip'] = temp['issuerCusip'].shift(1)
temp['changeBank'] = temp.apply(lambda x: True if x.leftLeadFirmName != x.lagLeftLeadFirmName and x.issuerCusip == x.lagissuerCusip else False, axis =1)
print('number of offerings that change bank from the previous offering', len(temp[temp.changeBank == True]))
temp.head(5)

number of offerings that change bank from the previous offering 2079

,issuerCusip,offeringPricingDate,leftLeadFirmName,lagLeftLeadFirmName,lagissuerCusip,changeBank
offeringId,,,,,,
bd9e5775-0981-48a0-87a0-01387de77e3f,000307108,2014-10-01,William Blair,NaN,NaN,False
82fb9a9d-f7a2-4759-92f6-32a8e247bfb3,000307108,2017-11-07,Raymond James,William Blair,000307108,True
76f2a97e-7b6a-4452-8c0a-8cbb5526cb7f,000307108,2017-11-14,Raymond James,Raymond James,000307108,False
6e6de148-cbfd-4e08-b5f8-fbffd5a12740,000380204,2020-10-21,Morgan Stanley,Raymond James,000307108,False
55581e92-12e6-4a99-bc75-824fb1a7b954,00081T108,2006-09-21,Credit Suisse,Morgan Stanley,000380204,False

I will choose the second definition of whether or not changed lead bank.

In [9]:
cmg_transformed = cmg_transformed.merge(temp[['changeBank']], how = 'left', left_index = True, right_index = True)

In [10]:
change = temp[temp.changeBank == True].groupby(['leftLeadFirmName','lagLeftLeadFirmName']).size().reset_index()
change.columns = ['from', 'to', 'count']
change.sort_values(by = 'count', ascending = False).iloc[1:10]

                    from                   to  count
396       Morgan Stanley  Goldman Sachs & Co.     50
397       Morgan Stanley          J.P. Morgan     46
294          J.P. Morgan  Goldman Sachs & Co.     45
300          J.P. Morgan       Morgan Stanley     42
245  Goldman Sachs & Co.          J.P. Morgan     41
387       Morgan Stanley      BofA Securities     37
139            Citigroup      BofA Securities     36
237  Goldman Sachs & Co.      BofA Securities     32
391       Morgan Stanley        Credit Suisse     31

<a id='transform'></a>
## 3. Transformation
- [Train test split](#split)
- [Column transformation](#trans)

In [14]:
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

<a id='split'></a>
### Train test split

Why do we want to do train-test split? In data science, what we are really trying to do is to learn patterns for the already knowns, and then try to apply the patterns we learn to the unknown part. 


The figure below is a great illustration for what we are trying to do here. In this competition, the test set(navy part) is the unknown part to you since you do not have the outcome variables for this part of the data. In fact, we are having you to predict the outcomes for this part! But given the data we provide for you, you fit a model. How do you know that you have trained a model that makes some sense, you need to first test the model with the knonws you have in hand.

In [11]:
y = cmg_transformed.filter(like = 'Post_')
X = cmg_transformed.loc[:, ~cmg_transformed.columns.isin(list(y))].drop(columns = ['offeringPricingDate', 'offeringSubSector', 'issuerCusip', 'issuerName', 'underwriters', 'leftLeadFirmId', 'leftLeadFirmName'])

In [17]:
from IPython.display import Image
Image(url="fig/train_test_split.png", width=1000, height=618)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

<a id='trans'></a>
### Column tranformation

In [16]:
numerical_cols = list(X.select_dtypes(include=np.number))
categorical_cols = [col for col in list(X) if col not in numerical_cols]
numerical_cols

['offeringDiscountToLastTrade',
 'offeringPrice',
 'Pre_15SharePrice',
 'Pre_14SharePrice',
 'Pre_13SharePrice',
 'Pre_12SharePrice',
 'Pre_11SharePrice',
 'Pre_10SharePrice',
 'Pre_9SharePrice',
 'Pre_8SharePrice',
 'Pre_7SharePrice',
 'Pre_6SharePrice',
 'Pre_5SharePrice',
 'Pre_4SharePrice',
 'Pre_3SharePrice',
 'Pre_2SharePrice',
 'Pre_1SharePrice',
 'totalBookrunners']

In [17]:
numerical_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown='ignore')
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)])

X_train_transformed = preprocessor.fit_transform(X_train)
X_test_transformed = preprocessor.fit_transform(X_test)
print(type(X_train_transformed), X_train_transformed.shape)

<class 'numpy.ndarray'> (5093, 36)

The ColumnTransformer has automatically transformed our pandas data frame to a numpy array. We could always transform them back to pandas data frame. After the transformation, we observe that for the numerical columns, the mean are now very close to 0, which is exactly what we wanted.

In [18]:
cols = numerical_cols + list(preprocessor.named_transformers_['cat'].get_feature_names(categorical_cols))
X_train_transformed = pd.DataFrame(X_train_transformed, columns = cols )
X_test_transformed = pd.DataFrame(X_test_transformed, columns = cols)
X_train_transformed.mean()

offeringDiscountToLastTrade             -3.032241e-17
offeringPrice                            2.746674e-18
Pre_15SharePrice                         2.552663e-17
Pre_14SharePrice                        -1.407125e-16
Pre_13SharePrice                         3.591385e-17
Pre_12SharePrice                        -6.195276e-17
Pre_11SharePrice                        -9.659137e-17
Pre_10SharePrice                         1.150987e-16
Pre_9SharePrice                          1.031093e-17
Pre_8SharePrice                         -3.183744e-17
Pre_7SharePrice                          4.999600e-17
Pre_6SharePrice                          6.316260e-17
Pre_5SharePrice                         -2.997362e-17
Pre_4SharePrice                         -1.778798e-17
Pre_3SharePrice                         -1.004607e-16
Pre_2SharePrice                          3.385385e-17
Pre_1SharePrice                          1.028804e-16
totalBookrunners                         1.088860e-16
offeringType_IPO                         3.396819e-01
offeringType_MARKETED_FO                 2.648734e-01
offeringType_OVERNIGHT_FO                1.932064e-01
offeringType_REGISTERED_BLOCK            1.456902e-01
offeringType_UNREGISTERED_BLOCK          5.654820e-02
offeringSector_Basic Materials           2.473984e-02
offeringSector_Communication Services    4.005498e-02
offeringSector_Consumer Cyclical         8.148439e-02
offeringSector_Consumer Defensive        3.318280e-02
offeringSector_Energy                    8.796387e-02
offeringSector_Financial Services        1.504025e-01
offeringSector_Healthcare                2.686040e-01
offeringSector_Industrials               7.775378e-02
offeringSector_Real Estate               9.365796e-02
offeringSector_Technology                1.264481e-01
offeringSector_Utilities                 1.570783e-02
changeBank_False                         7.580994e-01
changeBank_True                          2.419006e-01
dtype: float64

<a id='function'></a>
## 4. Put everything together

We have introducted multiples ways in engineering our features. However, isn't it more satsifying to have a single function that takes in the original data frame and outputs transformed data that can be directly put into models than running through all the cells above? The cell below is a function wrapper for all the engineering steps we had earlier.

In [19]:
def feature_engineering(df):
    '''given the cmg data, we want to return '''
    
    df = df.apply(lambda x: x.fillna(value=df['offeringPrice']))
    
    # how many offerings that have a change from the previous bank
    temp = df.filter(items = ['offeringId', 'issuerCusip', 'offeringPricingDate', 'leftLeadFirmName']).sort_values(by = ['issuerCusip', 'offeringPricingDate'])
    temp['lagLeftLeadFirmName'] = temp['leftLeadFirmName'].shift(1)
    temp['lagissuerCusip'] = temp['issuerCusip'].shift(1)
    temp['changeBank'] = temp.apply(lambda x: True if x.leftLeadFirmName != x.lagLeftLeadFirmName and x.issuerCusip == x.lagissuerCusip else False, axis =1)
    df = df.merge(temp[['changeBank']], how = 'left', left_index = True, right_index = True)
    
    y = df.filter(like = 'Post_')
    X = df.loc[:, ~df.columns.isin(list(y))].drop(columns = ['offeringPricingDate', 'offeringSubSector', 'issuerCusip', 'issuerName', 'underwriters', 'leftLeadFirmId', 'leftLeadFirmName'])
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)
    
    numerical_cols = list(X.select_dtypes(include=np.number))
    categorical_cols = [col for col in list(X) if col not in numerical_cols]
    numerical_transformer = StandardScaler()
    categorical_transformer = OneHotEncoder(handle_unknown='ignore')
    preprocessor = ColumnTransformer(
        transformers=[
        ('num', numerical_transformer, numerical_cols),
        ('cat', categorical_transformer, categorical_cols)])
    X_train_transformed = preprocessor.fit_transform(X_train)
    X_test_transformed = preprocessor.fit_transform(X_test)
    cols = numerical_cols + list(preprocessor.named_transformers_['cat'].get_feature_names(categorical_cols))
    X_train_transformed = pd.DataFrame(X_train_transformed, columns = cols, index = X_train.index )
    X_test_transformed = pd.DataFrame(X_test_transformed, columns = cols, index = X_test.index)
    
    return X_train_transformed, X_test_transformed, y_train, y_test

In [20]:
X_train_transformed, X_test_transformed, y_train, y_test = feature_engineering(cmg)

In [21]:
X_train_transformed.head()

,offeringDiscountToLastTrade,offeringPrice,Pre_15SharePrice,Pre_14SharePrice,Pre_13SharePrice,Pre_12SharePrice,Pre_11SharePrice,Pre_10SharePrice,Pre_9SharePrice,Pre_8SharePrice,...,offeringSector_Consumer Defensive,offeringSector_Energy,offeringSector_Financial Services,offeringSector_Healthcare,offeringSector_Industrials,offeringSector_Real Estate,offeringSector_Technology,offeringSector_Utilities,changeBank_False,changeBank_True
offeringId,,,,,,,,,,,,,,,,,,,,,
bad6b2ae-1beb-4a88-82aa-3b9117ead47c,0.136109,-0.282516,-0.288794,-0.292903,-0.281602,-0.282647,-0.281481,-0.265399,-0.282122,-0.296618,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
e64bc45a-3780-404f-a954-db6a40e39c7c,-0.336302,-0.529067,-0.494071,-0.481234,-0.487995,-0.495331,-0.493549,-0.494620,-0.495279,-0.494317,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
83132a36-51df-4b28-a44f-1538e5c15e35,0.202309,0.031385,-0.005405,-0.002868,0.003470,-0.007546,-0.008098,-0.010198,0.001397,0.012486,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
cca70347-894b-4272-87c9-90b919e21126,-1.405310,-0.492986,-0.484307,-0.472459,-0.485942,-0.484465,-0.483176,-0.475308,-0.482172,-0.480619,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2e9841d7-6209-4d98-9b50-045f83aee52b,-1.638802,-0.201936,0.003429,-0.017719,0.013049,0.028287,0.037313,0.007045,0.002777,0.002213,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0